### ISSUE TITLE
Edit on Github link from doc page is broken

### ISSUE THREAD

**Issue by natashadsilva** [IBMStreams/pypi.streamsx.elasticsearch#3]
From the doc homepage, I click "Edit on Github" and it brought me to this page, with a 404 error:

https://github.com/IBMStreams/pypi.streamsx.elasticsearch/blob/origin/master/package/docs/source/index.rst

**Comment by markheger** [comment]
Sometimes readthedocs adds "origin" in the URL to the gitHub page
Don't know the root cause for this. Seems to be a bug in readthedocs.
After changing the default version to 1.1.0, it is resolved.
